### ISSUE TITLE
pod 不成功

### ISSUE THREAD

**Issue by SeriouslyFunny** [daoseng33/DAONaviBar#1]
[!] Unable to find a specification for `DAONaviBar`

**Comment by daoseng33** [comment]
Try this:

I suppose that there is a problem with your pod master repo. Delete ir and download it again.

You can do:
```
pod repo remove master
pod setup
pod install
```
Or:
```
sudo rm -fr ~/.cocoapods/repos/master
pod setup
pod install
```

source link:
https://stackoverflow.com/questions/25913733/unable-to-find-a-specification-in-cocoapods
